version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: admin-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    ports:
        - "5173:5173"
        - "5174:5174"
        - "5175:5175"
    volumes:
      - ./:/var/www:cached  # comment when deploy
      - ./docker/php/php-local.ini:/usr/etc/php/conf.d/local.ini
      - ./docker/php/www.conf:/usr/etc/php-fpm.d/www.conf
    networks:
      - presign-url-network

  #Nginx Service
  webserver:
    image: nginx:1.21.6
    container_name: admin-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/public
      - ./storage:/var/www/storage
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - presign-url-network
    depends_on:
      - app

networks:
  presign-url-network:
    external: true
